Update README.md
wert-io/widget-initializer pull request #6
Opened 2021-12-09 13:43 UTC by QiaoMali

Added 'blockchain' parameter + made some copy fixes

@apples-father pls check if blockchain param description is correct and merge if  everything is ok

2021-12-10 09:55 UTC, apples-father requested changes

2021-12-10 09:55 UTC, apples-father commented on README.md
> +| **pk_id** | required for smart contracts | *string* | | | It'a always 'key1' |
Опечаточка `It'a`

2021-12-10 09:55 UTC, apples-father commented on README.md
> +| **commodities** | optional | *String* | | | Commodities that will be available in the widget. By default, all commodities are present. |
Я бы хотел сохранить информацию о том, как задавать значения: то есть `Comma separated commodity values` было важной частью предыдущего описания

2021-12-10 09:55 UTC, apples-father commented on README.md
> +| **pk_id** | required for smart contracts | *string* | | | It'a always 'key1' |
Плюс, по-моему, не надо такого писать: `It's always 'key1'`. Спрашивается, зачем нужна тогда эта настройка, если она всегда одна и та же?

Сейчас мы по каким-то причинам всегда даём **id** `key1`, но в любой момент это может измениться.

2021-12-10 09:55 UTC, apples-father commented on README.md
> +| **phone** | optional | *String* | | +11014321111 | User's phone number. Can be passed with or without + |
Возможно, имеет смысл упомянуть, что телефон в интернациональном формате

2021-12-10 09:58 UTC, QiaoMali commented on README.md
> +| **commodities** | optional | *String* | | | Commodities that will be available in the widget. By default, all commodities are present. |
bug, случайно ушло

2021-12-13 08:49 UTC, apples-father approved these changes

2021-12-15 13:11 UTC, merged